export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const FETCH_GITHUB_USER_ATTEMPT = 'FETCH_GITHUB_USER_ATTEMPT';
export const FETCH_GITHUB_USER_SUCCESS = 'FETCH_GITHUB_USER_SUCCESS';
export const FETCH_GITHUB_USER_FAIL = 'FETCH_GITHUB_USER_FAIL';
